# Generated by Django 2.1.4 on 2020-01-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_api', '0002_auto_20200104_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='marca',
            new_name='manufacturer',
        ),
    ]
